name: 'Build Setup'
description: 'Setup node'
runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'
        cache-dependency-path: cli/package-lock.json
    - name: Install dependencies
      uses: bahmutov/npm-install@v1
      with:
        working-directory: cli
        install-command: npm ci --ignore-scripts --prefer-offline --audit false
