########################################################################################################################
# Bonita open-api redirect
########################################################################################################################
# latest
[[redirects]]
from = "/latest/*"
to = "/0.0.11/:splat"
