name: Publish production
# Allow only one running and one pending instance of this workflow. See https://github.com/bonitasoft/bonita-documentation-site/issues/192
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency: ${{ github.workflow }}

on:
  workflow_dispatch:
    inputs:
      releases:
        description: 'List of bonita open Api to deploy'
        default: 0.0.11
        required: true
      latest:
        description: 'Latest release'
        default: 0.0.11
        required: false

permissions:
  # netlify: notify deployments
  deployments: write

jobs:
  deploy_to_netlify:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - name: Build site
        run: node cli/restdoc-site.js build -r ${{ inputs.releases }} -l ${{ inputs.latest }}
      - name: Create deploy message
        if: github.event_name == 'workflow_dispatch'
        run:
          echo "deploy_message=Deploy ${{github.sha}} from manual request" >> $GITHUB_ENV
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './build/'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-config-path: ./build/netlify.toml
          # no comment, we only publish to production, github commit status and environment are set correctly
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
#      - name: Send message to Slack channel
#        if: failure()
#        uses: slackapi/slack-github-action@v1.23.0
#        with:
#          channel-id: 'CCQGMR4ES'
#          payload: |
#            {
#              "blocks": [
#                {
#                  "type": "section",
#                  "text": {
#                    "type": "mrkdwn",
#                    "text": ":red_circle:  Publish rest api documentation in production failed. \n \n  @channel *We need someone* !"
#                  }
#                },
#                {
#                  "type": "section",
#                  "text": {
#                    "type": "mrkdwn",
#                    "text": "More details about the error <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}?check_suite_focus=true| here>"
#                  }
#                },
#                {
#                  "type": "divider"
#                },
#                {
#                  "type": "section",
#                  "text": {
#                    "type": "mrkdwn",
#                    "text": "_C’est pas grave de faire des erreurs. Par contre il ne faut pas les merger!_ :imp:"
#                  }
#                },
#                {
#                  "type": "context",
#                  "elements": [
#                    {
#                      "type": "plain_text",
#                      "text": "Author: Adrien L.",
#                      "emoji": true
#                    }
#                  ]
#                }
#              ]
#            }
#        env:
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
