name: Publish production
# Allow only one running and one pending instance of this workflow. See https://github.com/bonitasoft/bonita-documentation-site/issues/192
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
concurrency: ${{ github.workflow }}

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'cli/**/*'
      - 'site/**/*'
      - '.github/actions/build-setup/**/*'
      - '.github/workflows/publish-production.yml'

permissions:
  # netlify: notify deployments
  deployments: write

jobs:
  deploy_to_netlify:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Build Setup
        uses: ./.github/actions/build-setup
      - run: npm --prefix ./cli run test
      - name: Build site
        run: node cli/restdoc-site.js --config cli/restdoc-site.cfg.json build
      - name: Create deploy message
        if: github.event_name == 'workflow_dispatch'
        run:
          echo "deploy_message=Deploy ${{github.sha}} from manual request" >> $GITHUB_ENV
      - name: Create deploy message if push or pull request
        if: github.event_name == 'push'
        run:
          echo "deploy_message=Deploy ${{ github.sha }}" >> $GITHUB_ENV
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build/'
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: ${{ env.deploy_message }}
          netlify-config-path: ./build/netlify.toml
          # no comment, we only publish to production, github commit status and environment are set correctly
          enable-pull-request-comment: false
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 10
      - name: Send message to Slack channel
        if: ${{ failure() }}
        uses: bonitasoft/notify-slack-action@v1
        with:
          keeper-secret-config: ${{ secrets.KSM_CONFIG }}
          channel-id: CCQGMR4ES
          message: |
           :red_circle:  Publish rest api documentation in production failed.
           
           @channel *We need someone* !
           
           More details about the error <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}?check_suite_focus=true| here>      
